---@class opencode.events.Opts
---@field enabled? boolean Subscribe to SSE and dispatch `OpencodeEvent:*` autocmds.
---@field reload? boolean Reload buffers edited by OpenCode in real-time. Requires `vim.o.autoread = true`.
---@field permissions? opencode.events.permissions.Opts
